language: scala
install:
 # first let's build the libsecp256k1 jni lib
 - cd secp256k1
 - ./autogen.sh
 - ./configure --enable-jni --enable-experimental --enable-module-ecdh
 - make
 - cd ..
 # then we build the java/scala lib
 - sbt test:compile
script: 
 # test with bouncycastle
 - sbt test
 # test with libsecp256k1
 - export LD_LIBRARY_PATH=secp256k1/.libs
 - sbt test
scala:
- 2.11.12
- 2.12.6
jdk:
- oraclejdk8
