language: scala
before_install:
- wget http://mirror.ibcp.fr/pub/apache/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
- unzip -qq apache-maven-3.5.4-bin.zip
- export M2_HOME=$PWD/apache-maven-3.5.4
- export PATH=$M2_HOME/bin:$PATH
install:
 - sbt test:compile
script: 
 # test with bouncycastle
 - sbt test -Dfr.acinq.secp256k1.lib.name=foo
 # test with libsecp256k1
 - sbt test
scala:
- 2.11.12
- 2.12.10
- 2.13.1
jdk:
- openjdk8
- openjdk11
